[project]
name = "cbi-mcp-server"
version = "0.1.0"
description = "MCP Server for interacting with ChatCBI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx==0.28.1",
    "mcp[cli]==1.8.1",
    "python-dotenv==1.1.0",
]
